services:
  - type: web
    name: pcmmd-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: ALLOWED_ORIGINS
        value: https://pcmmd-frontend.vercel.app  # Đường dẫn frontend Vercel của bạn
    healthCheckPath: /
    autoDeploy: true
